@extends('admin.layout')
@section('content')
<link rel="stylesheet" href="/admin-overview.css?v=1">
@include('agency.sidebar')
<main class="workspace owner-dashboard"><h1>Dashboard Admin Agency</h1><p class="overview-subtitle">Kelola data pekerja, booking, subscription, dan aktivitas {{ $agency->name }}.</p>
<div class="overview-cards">@foreach([['Total Pekerja',$counts['workers'],'workers'],['Booking Aktif',$counts['active'],'bookings'],['Booking Selesai',$counts['completed'],'bookings'],['Subscription',['active'=>'Aktif','inactive'=>'Belum aktif','demo'=>'Demo'][$agency->subscription] ?? $agency->subscription,'agencies']] as [$label,$value,$icon])<div class="panel overview-card"><span class="overview-icon icon-{{ $loop->index }}">@include('admin.nav-icon',['name'=>$icon])</span><div><small>{{ $label }}</small><strong>{{ is_numeric($value) ? number_format($value,0,',','.') : $value }}</strong><span>{{ $icon === 'bookings' ? 'Transaksi aktual' : ($icon === 'workers' ? 'Pekerja naungan agency' : 'Status langganan saat ini') }}</span></div></div>@endforeach</div>
<div class="overview-grid"><section class="panel"><div class="overview-title"><h2>Tren Booking</h2><form method="get"><select name="days" aria-label="Periode tren" onchange="this.form.submit()">@foreach([30,90,180] as $period)<option value="{{ $period }}" @selected($days === $period)>{{ $period }} hari terakhir</option>@endforeach</select><noscript><button>Tampilkan</button></noscript></form></div><p class="chart-caption">{{ $trend->sum('total') }} booking baru · tidak termasuk demo</p>
@php($maximum = max(1,$trend->max('total')))
@php($points = $trend->map(fn($item,$index) => (45+$index*510/max(1,$trend->count()-1)).','. (190-$item['total']/$maximum*150))->implode(' '))
<svg class="booking-chart" viewBox="0 0 580 230" role="img" aria-label="Tren booking agency {{ $days }} hari terakhir">
@foreach([0,0.5,1] as $level)<line x1="45" x2="555" y1="{{ 190-$level*150 }}" y2="{{ 190-$level*150 }}" stroke="#e3ebe5"/><text x="5" y="{{ 194-$level*150 }}">{{ round($maximum*$level,1) }}</text>@endforeach
<polygon points="45,190 {{ $points }} 555,190" fill="#e7f2ea"/><polyline points="{{ $points }}" fill="none" stroke="#246c56" stroke-width="3"/>
@foreach($trend as $item)<circle cx="{{ 45+$loop->index*510/max(1,$trend->count()-1) }}" cy="{{ 190-$item['total']/$maximum*150 }}" r="2" fill="#246c56"><title>{{ $item['date'] }}: {{ $item['total'] }} booking</title></circle>@endforeach
<text x="45" y="218">{{ $trend->first()['date'] }}</text><text x="555" y="218" text-anchor="end">{{ $trend->last()['date'] }}</text></svg><details class="chart-data"><summary>Lihat data harian</summary><div>@foreach($trend as $item)<p>{{ $item['date'] }} <strong>{{ $item['total'] }}</strong></p>@endforeach</div></details></section>
<section class="panel"><h2>Status Pekerja</h2><div class="verification-chart"><svg viewBox="0 0 120 120" role="img" aria-label="Status pekerja naungan"><circle cx="60" cy="60" r="46" fill="none" stroke="#edf0ec" stroke-width="13"/>
@php($offset = 0)
@php($colors = ['#37876c','#c8d1cb','#f0cd69','#e78383'])
@foreach($workerStatuses as $label=>$count)
@php($percent = $counts['workers'] ? $count/$counts['workers']*100 : 0)
<circle cx="60" cy="60" r="46" pathLength="100" fill="none" stroke="{{ $colors[$loop->index] }}" stroke-width="13" stroke-dasharray="{{ $percent }} {{ 100-$percent }}" stroke-dashoffset="{{ -$offset }}" transform="rotate(-90 60 60)"/>
@php($offset += $percent)
@endforeach
<text x="60" y="58" text-anchor="middle" class="donut-total">{{ $counts['workers'] }}</text><text x="60" y="73" text-anchor="middle">Pekerja</text></svg><ul>@foreach($workerStatuses as $label=>$count)<li><span class="dot" style="background:{{ $colors[$loop->index] }}"></span>{{ $label }}<strong>{{ $count }}</strong></li>@endforeach</ul></div><small>Aktif: terverifikasi dan tersedia untuk bekerja.</small></section>
<section class="panel" id="bookings"><div class="overview-title"><h2>Booking Terbaru</h2></div><div class="table-wrap"><table class="activity-table"><thead><tr><th>ID</th><th>Keluarga / Pekerja</th><th>Layanan</th><th>Tanggal Mulai</th><th>Status</th></tr></thead><tbody>@forelse($recent as $booking)<tr><td>#{{ $booking->id }}</td><td>{{ $booking->family_name ?? '—' }}<small>{{ $booking->worker_name ?? '—' }}</small></td><td>{{ ['hourly'=>'Per Jam','daily'=>'Harian','monthly'=>'Bulanan'][$booking->rate_unit] ?? $booking->rate_unit }}</td><td>{{ \Carbon\Carbon::parse($booking->starts_at)->format('d M Y') }}</td><td>{{ ['requested'=>'Diminta','accepted'=>'Diterima','in_progress'=>'Berlangsung','completed'=>'Selesai','cancelled'=>'Dibatalkan'][$booking->status] ?? $booking->status }}</td></tr>@empty<tr><td colspan="5">Belum ada booking aktual.</td></tr>@endforelse</tbody></table></div>
@include('admin.pagination',['page'=>$recent,'anchor'=>'bookings'])
</section><section class="panel"><h2>Notifikasi</h2><p class="chart-caption">Ringkasan yang perlu ditindaklanjuti.</p>@foreach([['Dokumen menunggu verifikasi',$pendingDocuments,route('agency.portal',['tab'=>'documents'])],['Pekerja dalam verifikasi',$workerStatuses['Dalam verifikasi'],route('agency.portal',['tab'=>'workers','verification'=>'pending'])],['Booking menunggu pembayaran',$unpaid,'#bookings']] as [$label,$count,$url])<a class="overview-notification" href="{{ $url }}"><span>{{ $label }}</span><strong>{{ $count }}</strong></a>@endforeach<a class="overview-notification" href="{{ route('agency.portal',['tab'=>'profile']) }}">Status agency: {{ ['verified'=>'Terverifikasi','pending'=>'Belum Terverifikasi','rejected'=>'Ditolak'][$agency->verification] ?? $agency->verification }}</a></section></div></main>
@endsection
