@extends('admin.layout')
@section('content')
<link rel="stylesheet" href="/agency-portal.css?v=1">
<aside><x-asista-logo /><p class="eyebrow">AGENCY MANAGEMENT</p><nav><a class="active" href="{{ route('agency.portal') }}">▣ Agency</a></nav><form method="post" action="/logout">@csrf<button class="secondary">Keluar</button></form></aside>
<main class="workspace agency-workspace"><header><div><p class="eyebrow">ASISTA / AGENCY</p><h1>Agency</h1><p>Kelola informasi agency, pengelola, dokumen, tarif, dan data pekerja Anda.</p></div><span class="badge">{{ auth()->user()->name }}</span></header>
@if(session('success'))<div class="notice" role="status">{{ session('success') }}</div>@endif
@foreach($errors->all() as $error)<p class="error" role="alert">{{ $error }}</p>@endforeach
<nav class="agency-tabs" aria-label="Pengaturan agency">@foreach(['profile'=>'Profil Agency','manager'=>'Pengelola Agency','documents'=>'Dokumen & Legalitas','rates'=>'Tarif & Fee','workers'=>'Data Pekerja'] as $key=>$label)<a class="{{ $key === $tab ? 'active' : '' }}" href="{{ route('agency.portal',['tab'=>$key]) }}" @if($key === $tab) aria-current="page" @endif>{{ $label }}</a>@endforeach</nav>
@php($statuses = ['pending'=>'Menunggu verifikasi','verified'=>'Terverifikasi','rejected'=>'Ditolak'])
@if($tab === 'profile')
<div class="agency-profile-grid"><section class="panel"><h2>Informasi Agency</h2><h3>{{ $agency->name }}</h3><small>Terdaftar {{ \Carbon\Carbon::parse($agency->created_at)->format('d M Y') }}</small><form class="agency-fields" method="post" action="{{ route('agency.profile') }}">@csrf
@foreach(['company_name'=>'Nama Agency','city'=>'Kota / Kabupaten','address'=>'Alamat Perusahaan','company_phone'=>'Telepon / WhatsApp','company_email'=>'Email Perusahaan','website'=>'Website (opsional)','social_media'=>'Media Sosial (opsional)'] as $key=>$label)<label>{{ $label }}<input name="{{ $key }}" value="{{ old($key,$details[$key] ?? ($key === 'company_name' ? $agency->name : ($key === 'city' ? $agency->city : ''))) }}" @required(!in_array($key,['website','social_media'])) type="{{ $key === 'company_email' ? 'email' : ($key === 'website' ? 'url' : 'text') }}"></label>@endforeach
<label class="wide">Deskripsi Agency<textarea name="description" maxlength="2000">{{ old('description',$details['description'] ?? '') }}</textarea></label><button>Simpan profil</button></form></section><section class="panel"><h3>Status Agency</h3><span class="badge">{{ $statuses[$agency->verification] ?? $agency->verification }}</span><p>Perubahan profil atau unggahan legalitas akan diperiksa kembali oleh tim ASISTA.</p><small>Nomor legalitas: {{ $agency->legal_number }}</small></section></div>
@elseif($tab === 'manager')
<section class="panel"><h2>Data Pengelola Agency</h2><p>Pengelola utama yang memiliki akses akun agency ini.</p><div class="table-wrap"><table><thead><tr><th>Nama</th><th>Jabatan</th><th>Email masuk</th><th>Telepon</th><th>Akses</th></tr></thead><tbody><tr><td>{{ auth()->user()->name }}</td><td>{{ $details['position'] ?? 'Belum diisi' }}</td><td>{{ auth()->user()->email }}</td><td>{{ $details['phone'] ?? 'Belum diisi' }}</td><td>Owner Agency</td></tr></tbody></table></div><form class="agency-fields" method="post" action="{{ route('agency.manager') }}">@csrf
@foreach(['name'=>'Nama Pengelola','position'=>'Jabatan','phone'=>'Telepon','manager_address'=>'Alamat Domisili (opsional)'] as $key=>$label)<label>{{ $label }}<input name="{{ $key }}" value="{{ old($key,$key === 'name' ? auth()->user()->name : ($details[$key] ?? '')) }}" @required($key !== 'manager_address')></label>@endforeach<button>Simpan pengelola</button></form></section>
@elseif($tab === 'documents')
<section class="panel"><h2>Dokumen & Legalitas</h2><p>Dokumen privat agency Anda. Klik Lihat untuk membuka berkas. Setiap akses dicatat.</p><form class="agency-upload" method="post" enctype="multipart/form-data" action="{{ route('agency.documents.upload') }}">@csrf<label>Jenis dokumen<select name="document_type">@foreach(\App\Http\Controllers\AgencyRegistrationController::DOCUMENTS as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></label><label>PDF / JPG / PNG, maks. 5 MB<input type="file" name="document" accept=".pdf,.jpg,.jpeg,.png" required></label><button>Unggah dokumen</button></form><div class="agency-document-grid">@forelse($documents as $document)<article class="agency-document"><h3>{{ \App\Http\Controllers\AgencyRegistrationController::DOCUMENTS[$document->document_type] ?? 'Dokumen pendukung' }}</h3><span class="badge">{{ $statuses[$document->status] ?? $document->status }}</span><p>{{ $document->original_name }}</p><small>{{ $document->created_at }}</small><p><a class="button secondary" target="_blank" rel="noopener" href="{{ route('agency.document',$document->id) }}">Lihat ↗</a></p>@if($document->note)<p>{{ $document->note }}</p>@endif</article>@empty<p>Belum ada dokumen.</p>@endforelse</div></section>
@elseif($tab === 'rates')
<section class="panel"><h2>Pengaturan Tarif Pekerja</h2><p>Tarif pekerja per jam, hari, atau bulan. Fee agency berupa nominal rupiah sekali per booking.</p><form class="agency-fields" method="post" action="{{ route('agency.rates') }}">@csrf<label>Jenis Pekerjaan<select name="category"><option value="babysitter">Babysitter</option><option value="art">ART</option></select></label><label>Durasi<select name="rate_unit"><option value="hourly">Per Jam</option><option value="daily">Harian</option><option value="monthly">Bulanan</option></select></label><label>Pola Kerja<select name="arrangement"><option value="live_out">PP / Live-out</option><option value="live_in">Live-in</option></select></label><label>Tarif Pekerja (Rp)<input type="number" name="rate" min="10000" max="100000000" required></label><label>Fee Agency / Booking (Rp)<input type="number" name="agency_fee" min="0" max="100000000" required></label><button>Simpan / perbarui tarif</button></form><p><small>Kombinasi jenis, durasi, dan pola kerja yang sama akan diperbarui. Penerapan hanya tersedia setelah agency terverifikasi.</small></p><div class="table-wrap"><table><thead><tr><th>Jenis</th><th>Durasi</th><th>Pola</th><th>Tarif</th><th>Fee Agency</th><th>Tindakan</th></tr></thead><tbody>@forelse($rates as $rate)<tr><td>{{ strtoupper($rate->category) }}</td><td>{{ ['hourly'=>'Per Jam','daily'=>'Harian','monthly'=>'Bulanan'][$rate->rate_unit] }}</td><td>{{ $rate->arrangement }}</td><td>Rp {{ number_format($rate->rate,0,',','.') }}</td><td>Rp {{ number_format($rate->agency_fee,0,',','.') }}</td><td><form method="post" action="{{ route('agency.rates.apply',$rate->id) }}">@csrf<button @disabled($agency->verification !== 'verified')>Terapkan ke pekerja sesuai</button></form></td></tr>@empty<tr><td colspan="6">Belum ada pengaturan tarif.</td></tr>@endforelse</tbody></table></div></section>
@elseif($tab === 'workers')
<section class="panel"><h2>Data Pekerja Naungan Agency</h2><form class="agency-upload" method="get"><input type="hidden" name="tab" value="workers"><input name="q" value="{{ request('q') }}" placeholder="Cari nama atau kota pekerja" aria-label="Cari pekerja"><button>Cari</button><a href="{{ route('agency.portal',['tab'=>'workers']) }}">Reset</a></form><div class="table-wrap"><table><thead><tr><th>Nama</th><th>Jenis</th><th>Lokasi</th><th>Pengalaman</th><th>Status</th><th>Tarif / Fee</th><th>Detail</th></tr></thead><tbody>@forelse($workers as $worker)<tr><td><strong>{{ $worker->name }}</strong></td><td>{{ strtoupper($worker->category) }}</td><td>{{ $worker->city }}</td><td>{{ $worker->experience_years }} tahun</td><td>{{ $statuses[$worker->verification] ?? $worker->verification }}</td><td>Rp {{ number_format($worker->rate,0,',','.') }} / {{ $worker->rate_unit }}<br><small>Fee Rp {{ number_format($worker->agency_fee,0,',','.') }}</small></td><td><a class="button secondary" href="{{ route('agency.worker',$worker->id) }}">Lihat CV & video →</a></td></tr>@empty<tr><td colspan="7">Belum ada pekerja yang sesuai. Hubungan agency–pekerja mengikuti persetujuan pada aplikasi ASISTA.</td></tr>@endforelse</tbody></table></div>
@include('admin.pagination',['page'=>$workers,'anchor'=>''])
</section>@endif
</main>
@endsection
