<link rel="stylesheet" href="/agency-rates.css?v=1">
@php($editing = $rates->firstWhere('id', (int) request('edit_rate')))
<section class="panel agency-rate-panel"><div class="rate-heading"><div><h2>Pengaturan Tarif Pekerja</h2><p>Atur tarif pekerja naungan agency berdasarkan jenis pekerjaan, durasi, dan pola kerja.</p></div><a class="button" href="{{ route('agency.portal',['tab'=>'rates','add'=>1]) }}">+ Tambah Tarif</a></div>
@if(request('add') || $editing || $errors->any())
<form class="rate-editor" method="post" action="{{ route('agency.rates') }}">@csrf
<label>Jenis Pekerjaan<select name="category">@foreach(['babysitter'=>'Babysitter','art'=>'ART'] as $value=>$label)<option value="{{ $value }}" @selected(old('category',$editing->category ?? '') === $value)>{{ $label }}</option>@endforeach</select></label>
<label>Tipe Layanan<select name="rate_unit">@foreach(['hourly'=>'Per Jam','daily'=>'Per Hari','monthly'=>'Bulanan'] as $value=>$label)<option value="{{ $value }}" @selected(old('rate_unit',$editing->rate_unit ?? '') === $value)>{{ $label }}</option>@endforeach</select></label>
<label>Pola Kerja<select name="arrangement">@foreach(['live_out'=>'PP / Live-out','live_in'=>'Live-in'] as $value=>$label)<option value="{{ $value }}" @selected(old('arrangement',$editing->arrangement ?? '') === $value)>{{ $label }}</option>@endforeach</select></label>
<label>Tarif (Rp)<input name="rate" type="number" min="10000" max="100000000" value="{{ old('rate',$editing->rate ?? '') }}" required></label><label>Fee / Booking (Rp)<input name="agency_fee" type="number" min="0" max="100000000" value="{{ old('agency_fee',$editing->agency_fee ?? '') }}" required></label><div><button>Simpan tarif</button><a href="{{ route('agency.portal',['tab'=>'rates']) }}">Batal</a></div>
<small>Kombinasi jenis, layanan, dan pola kerja yang sama akan diperbarui. Kombinasi baru akan menambahkan tarif.</small></form>
@endif
<div class="table-wrap"><table class="rate-table"><thead><tr><th>No.</th><th>Jenis Pekerjaan</th><th>Tipe Layanan</th><th>Pola Kerja</th><th>Tarif (Rp)</th><th>Fee Agency (Rp)</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
@forelse($rates as $rate)<tr><td>{{ $loop->iteration }}</td><td>{{ $rate->category === 'art' ? 'ART' : 'Babysitter' }}</td><td>{{ ['hourly'=>'Per Jam','daily'=>'Per Hari','monthly'=>'Bulanan'][$rate->rate_unit] }}</td><td>{{ $rate->arrangement === 'live_in' ? 'Live-in' : 'PP / Live-out' }}</td><td>{{ number_format($rate->rate,0,',','.') }}</td><td>{{ number_format($rate->agency_fee,0,',','.') }} <small>/ booking</small></td><td><span class="rate-status">Tersimpan</span></td><td><div class="rate-actions"><a href="{{ route('agency.portal',['tab'=>'rates','edit_rate'=>$rate->id]) }}" aria-label="Edit tarif {{ $rate->category }} {{ $rate->rate_unit }} {{ $rate->arrangement }}">✎ Edit</a><form method="post" action="{{ route('agency.rates.apply',$rate->id) }}">@csrf<button @disabled($agency->verification !== 'verified') title="Terapkan ke pekerja dengan jenis, durasi, dan pola kerja yang sama">Terapkan</button></form></div></td></tr>
@empty<tr><td colspan="8" class="empty">Belum ada tarif. Klik Tambah Tarif untuk memulai.</td></tr>@endforelse
</tbody></table></div><p class="rate-help">Fee agency dikenakan sekali per booking. Klik Terapkan untuk memperbarui pekerja yang sesuai; booking lama tidak berubah. Agency harus terverifikasi untuk menerapkan tarif.</p></section>
