@extends('admin.layout')
@section('content')
<link rel="stylesheet" href="/agency-portal.css?v=1">
<main class="agency-cv"><a href="{{ route('agency.portal',['tab'=>'workers']) }}">← Kembali ke Data Pekerja</a>
@if(session('success'))<p class="notice">{{ session('success') }}</p>@endif
@foreach($errors->all() as $error)<p class="error">{{ $error }}</p>@endforeach
<section class="panel"><p class="eyebrow">ASISTA / CV PEKERJA</p>@if($hasPhoto)<img class="agency-worker-photo" src="{{ route('agency.worker.photo',$worker->id) }}" alt="Foto {{ $worker->name }}">@endif<h1>{{ $worker->name }}</h1><p>{{ strtoupper($worker->category) }} · {{ $worker->city }} · {{ $worker->experience_years }} tahun pengalaman</p><span class="badge">{{ ['verified'=>'Terverifikasi','pending'=>'Menunggu verifikasi','rejected'=>'Ditolak'][$worker->verification] ?? $worker->verification }}</span><p>Rp {{ number_format($worker->rate,0,',','.') }} / {{ $worker->rate_unit }} · Fee agency Rp {{ number_format($worker->agency_fee,0,',','.') }} / booking</p></section>
<div class="agency-profile-grid"><div><section class="panel"><h2>Tentang Saya</h2><p>{{ $worker->bio }}</p><h3>Keahlian</h3>@foreach(json_decode($worker->skills,true) ?? [] as $skill)<span class="badge">{{ $skill }}</span>@endforeach<h3>Sertifikasi</h3>@forelse(json_decode($worker->certifications ?? '[]',true) ?? [] as $certificate)<p>{{ $certificate }}</p>@empty<p>Belum ada sertifikasi.</p>@endforelse<h3>Ketersediaan</h3><p>{{ $worker->available ? 'Tersedia' : 'Tidak tersedia' }} · {{ $worker->arrangement === 'live_in' ? 'Live-in' : 'PP / Live-out' }}</p></section><section class="panel"><h2>Riwayat Kerja</h2><p>Booking selesai melalui agency Anda.</p>@forelse($history as $booking)<article><strong>{{ $booking->starts_at }} – {{ $booking->ends_at }}</strong><p>{{ $booking->scope }}</p></article>@empty<p>Belum ada riwayat pekerjaan selesai.</p>@endforelse
@include('admin.cv-pagination',['page'=>$history,'anchor'=>''])
</section></div><section class="panel"><h2>Video Perkenalan</h2>@if($worker->video_path)<video controls preload="metadata" src="{{ route('agency.video',$worker->id) }}" style="width:100%;border-radius:12px"></video>@else<p>Belum ada video pekerja.</p>@endif<form method="post" enctype="multipart/form-data" action="{{ route('agency.video.upload',$worker->id) }}">@csrf<label>Unggah / ganti video (MP4 atau WebM, maks. 20 MB)<input type="file" name="video" accept=".mp4,.webm" required></label><button>Simpan video</button></form><small>Unggah video yang telah disetujui pekerja untuk digunakan sebagai portofolio.</small></section></div></main>
@endsection
