<link rel="stylesheet" href="/agency-workers.css?v=1">
<section class="panel agency-worker-list"><div class="agency-worker-title"><h2>Data Pekerja Naungan Agency</h2><p>Kelola data pekerja yang terdaftar di agency Anda.</p></div>
<form class="agency-worker-filters" method="get" action="{{ route('agency.portal') }}"><input type="hidden" name="tab" value="workers"><input name="q" value="{{ request('q') }}" placeholder="Cari nama pekerja..." aria-label="Cari pekerja"><select name="category" aria-label="Jenis pekerjaan"><option value="">Jenis pekerjaan</option>@foreach(['art'=>'ART','babysitter'=>'Babysitter'] as $key=>$label)<option value="{{ $key }}" @selected(request('category') === $key)>{{ $label }}</option>@endforeach</select><select name="verification" aria-label="Status verifikasi"><option value="">Status verifikasi</option>@foreach(['verified'=>'Terverifikasi','pending'=>'Menunggu','rejected'=>'Ditolak'] as $key=>$label)<option value="{{ $key }}" @selected(request('verification') === $key)>{{ $label }}</option>@endforeach</select><select name="city" aria-label="Lokasi"><option value="">Lokasi</option>@foreach($cities as $city)<option @selected(request('city') === $city)>{{ $city }}</option>@endforeach</select><button>Terapkan</button><a href="{{ route('agency.portal',['tab'=>'workers']) }}">Reset</a></form>
<div class="table-wrap"><table class="agency-worker-table"><thead><tr><th>Foto</th><th>Nama</th><th>Jenis Pekerjaan</th><th>Lokasi</th><th>Pengalaman</th><th>Status Verifikasi</th><th>Aksi</th></tr></thead><tbody>
@forelse($workers as $worker)<tr><td>@if($worker->photo_id)<img class="agency-worker-avatar" src="{{ route('agency.worker.photo',$worker->id) }}" alt="Foto {{ $worker->name }}" loading="lazy">@else<span class="agency-worker-avatar initials" aria-label="Foto belum tersedia">{{ mb_strtoupper(mb_substr($worker->name,0,1)) }}</span>@endif</td><td><a class="agency-worker-name" href="{{ route('agency.worker',$worker->id) }}">{{ $worker->name }}</a></td><td>{{ $worker->category === 'art' ? 'ART' : 'Babysitter' }}</td><td>{{ $worker->city }}</td><td>{{ $worker->experience_years }} tahun</td><td><span class="worker-verification {{ $worker->verification }}">{{ ['verified'=>'Terverifikasi','pending'=>'Menunggu','rejected'=>'Ditolak'][$worker->verification] ?? $worker->verification }}</span></td><td><a class="agency-worker-view" href="{{ route('agency.worker',$worker->id) }}" aria-label="Lihat CV dan video {{ $worker->name }}">▤ Lihat</a></td></tr>
@empty<tr><td colspan="7" class="empty">Tidak ada pekerja yang sesuai filter.</td></tr>@endforelse
</tbody></table></div>
@include('admin.pagination',['page'=>$workers,'anchor'=>''])
<p class="agency-worker-help">Penambahan pekerja mengikuti persetujuan hubungan agency–pekerja melalui aplikasi ASISTA.</p></section>
