@extends('admin.layout')
@section('content')
<link rel="stylesheet" href="/agency-portal.css?v=3"><link rel="stylesheet" href="/agency-documents.css?v=2"><link rel="stylesheet" href="/agency-rates.css?v=2"><link rel="stylesheet" href="/verification.css?v=1">
<main style="max-width:1400px;margin:auto;padding:24px">
<a href="/admin?section=agencies">← Kembali ke daftar Agency</a><header><p class="eyebrow">ASISTA / CMS ADMIN / AGENCY</p><h1>{{ $profile->name ?? $details['company_name'] ?? $user->name }}</h1><p>Hanya lihat. Pengubahan data dilakukan oleh agency yang bersangkutan.</p></header>
<nav class="agency-tabs" aria-label="Detail agency">@foreach(['profile'=>'Profil Agency','manager'=>'Pengelola Agency','documents'=>'Dokumen & Legalitas','rates'=>'Tarif & Fee','workers'=>'Data Pekerja'] as $key=>$label)<a class="{{ $tab === $key ? 'active' : '' }}" href="{{ route('admin.registrant',['id'=>$user->id,'tab'=>$key]) }}" @if($tab === $key) aria-current="page" @endif>{{ $label }}</a>@endforeach</nav>
@php($statuses = ['verified'=>'Terverifikasi','pending'=>'Belum Terverifikasi','rejected'=>'Ditolak'])
@if($tab === 'profile')
<div class="agency-profile-grid agency-profile-summary"><section class="panel"><div class="agency-information-heading"><span class="agency-building">@include('admin.nav-icon',['name'=>'agencies'])</span><div><h2>Informasi Agency</h2><h3>{{ $profile->name ?? $details['company_name'] ?? $user->name }}</h3><small>Terdaftar {{ \Carbon\Carbon::parse($user->created_at)->format('d M Y') }}</small></div></div><dl class="agency-information-list">
@foreach(['company_email'=>'Email Perusahaan','company_phone'=>'Nomor Telepon','website'=>'Website','social_media'=>'Media Sosial','city'=>'Kota','address'=>'Alamat','legal_number'=>'Nomor Legalitas','business_type'=>'Bentuk Badan Usaha','kbli'=>'KBLI','company_npwp'=>'NPWP Perusahaan','description'=>'Deskripsi Agency'] as $key=>$label)<dt>{{ $label }}</dt><dd>{{ ($key === 'city' ? ($profile->city ?? $details[$key] ?? null) : ($key === 'legal_number' ? ($profile->legal_number ?? $details[$key] ?? null) : ($details[$key] ?? null))) ?: 'Belum diisi' }}</dd>@endforeach
</dl></section><section class="panel"><h3>Status Agency</h3><span class="agency-state state-{{ $profile->verification ?? $user->verification }}">{{ $statuses[$profile->verification ?? $user->verification] ?? 'Belum Terverifikasi' }}</span><p>Email pengelola: {{ $user->email_verified_at ? 'Terverifikasi' : 'Belum terverifikasi' }}</p><small>Perubahan profil dan dokumen dilakukan melalui CMS agency.</small></section></div>
@elseif($tab === 'manager')
<section class="panel agency-managers"><h2>Data Pengelola Agency</h2><div class="table-wrap"><table class="agency-manager-table"><thead><tr><th>No.</th><th>Nama</th><th>Jabatan</th><th>Email</th><th>Nomor Telepon</th><th>Akses</th></tr></thead><tbody><tr><td>1</td><td>{{ $user->name }}</td><td>{{ $details['position'] ?? 'Belum diisi' }}</td><td>{{ $user->email }}</td><td>{{ $details['phone'] ?? 'Belum diisi' }}</td><td>Owner Agency</td></tr></tbody></table></div><p>Alamat pengelola: {{ $details['manager_address'] ?? 'Belum diisi' }}</p></section>
@elseif($tab === 'documents')
<section class="panel agency-legal"><h2>Dokumen & Legalitas</h2><p>Dokumen privat. Setiap akses berkas dicatat dalam audit trail.</p><div class="legal-grid">@forelse($documents->sortByDesc('id')->unique('document_type') as $document)<article class="legal-card"><h3>{{ \App\Http\Controllers\AgencyRegistrationController::DOCUMENTS[$document->document_type] ?? 'Dokumen pendukung' }}</h3><span class="legal-badge {{ $document->status === 'verified' ? 'verified' : '' }}">{{ $statuses[$document->status] ?? $document->status }}</span><div class="legal-card-body">@if(in_array($document->mime_type,['image/jpeg','image/png']))<button type="button" class="legal-thumbnail" data-preview="{{ route('admin.document',$document->id) }}" data-title="{{ $document->original_name }}" aria-label="Perbesar {{ $document->original_name }}"><img src="{{ route('admin.document',$document->id) }}" alt="{{ $document->original_name }}" loading="lazy"></button>@endif<div><small>{{ $document->created_at }}</small><div class="legal-actions"><a target="_blank" rel="noopener" href="{{ route('admin.document',$document->id) }}">Lihat ↗</a></div></div></div><p class="legal-note">{{ $document->original_name }}<br>{{ $document->note }}</p></article>@empty<p>Belum ada dokumen.</p>@endforelse</div></section>
<dialog id="document-modal" aria-labelledby="document-modal-title"><div class="document-modal-header"><h2 id="document-modal-title">Preview dokumen</h2><button type="button" id="document-modal-close">Tutup ×</button></div><img id="document-modal-image" alt=""><a id="document-modal-original" target="_blank" rel="noopener">Buka ukuran asli ↗</a></dialog><script src="/verification.js?v=1" defer></script>
@elseif($tab === 'rates')
<section class="panel agency-rate-panel"><h2>Pengaturan Tarif Pekerja</h2><div class="table-wrap"><table class="rate-table"><thead><tr><th>Jenis Pekerjaan</th><th>Tipe Layanan</th><th>Pola Kerja</th><th>Tarif (Rp)</th><th>Fee / Booking (Rp)</th></tr></thead><tbody>@forelse($rates as $rate)<tr><td>{{ $rate->category === 'art' ? 'ART' : 'Babysitter' }}</td><td>{{ ['hourly'=>'Per Jam','daily'=>'Per Hari','monthly'=>'Bulanan'][$rate->rate_unit] }}</td><td>{{ $rate->arrangement === 'live_in' ? 'Live-in' : 'PP / Live-out' }}</td><td>{{ number_format($rate->rate,0,',','.') }}</td><td>{{ number_format($rate->agency_fee,0,',','.') }}</td></tr>@empty<tr><td colspan="5">Belum ada tarif agency.</td></tr>@endforelse</tbody></table></div></section>
@else
<section class="panel"><h2>Data Pekerja Naungan Agency</h2><div class="table-wrap"><table><thead><tr><th>Nama</th><th>Jenis</th><th>Lokasi</th><th>Pengalaman</th><th>Status</th><th>Detail</th></tr></thead><tbody>@forelse($agencyWorkers as $worker)<tr><td>{{ $worker->name }}</td><td>{{ $worker->category === 'art' ? 'ART' : 'Babysitter' }}</td><td>{{ $worker->city }}</td><td>{{ $worker->experience_years }} tahun</td><td>{{ $statuses[$worker->verification] ?? $worker->verification }}</td><td><x-admin-document-button href="{{ route('admin.registrant',$worker->user_id) }}" /></td></tr>@empty<tr><td colspan="6">Belum ada pekerja naungan.</td></tr>@endforelse</tbody></table></div></section>
@endif
</main>
@endsection
