<link rel="stylesheet" href="/admin-bookings.css?v=1">
<div class="table-wrap"><table class="bookings-table"><thead><tr><th>Booking</th><th>Keluarga / Pekerja</th><th>Jadwal</th><th>Status</th><th>Total</th><th>Detail</th></tr></thead><tbody>
@forelse($rows as $row)<tr><td><strong>#{{ $row->id }}</strong>@if($row->is_demo)<small class="booking-pill demo">DEMO</small>@endif</td><td><strong>{{ $row->worker_name }}</strong><small>Keluarga: {{ $row->family_name }}</small><small>{{ $row->agency_name ?? 'Pekerja mandiri' }}</small></td><td>{{ \Carbon\Carbon::parse($row->starts_at)->format('d M Y H:i') }}<small>{{ $row->units }} {{ ['hourly'=>'jam','daily'=>'hari','monthly'=>'bulan'][$row->rate_unit] ?? $row->rate_unit }}</small></td><td><span class="booking-pill">{{ ['requested'=>'Diminta','accepted'=>'Diterima','in_progress'=>'Berlangsung','completed'=>'Selesai','cancelled'=>'Dibatalkan'][$row->status] ?? $row->status }}</span><small class="booking-pill {{ $row->payment_status === 'paid' ? 'paid' : 'unpaid' }}">{{ ['paid'=>'Dibayar','unpaid'=>'Belum dibayar','refund'=>'Refund'][$row->payment_status] ?? $row->payment_status }}</small></td><td class="booking-total"><strong>Rp {{ number_format($row->total,0,',','.') }}</strong><small>Fee ASISTA Rp {{ number_format($row->platform_fee,0,',','.') }}</small></td><td><details class="booking-detail"><summary>Lihat rincian</summary><div>
<h3>Booking #{{ $row->id }}</h3><p>{{ $row->scope }}</p><p>Selesai: {{ \Carbon\Carbon::parse($row->ends_at)->format('d M Y H:i') }}</p>
<dl><dt>Tarif saat booking Rp {{ number_format($row->worker_pay / max(1,$row->units),0,',','.') }} × {{ $row->units }}</dt><dd>Rp {{ number_format($row->worker_pay,0,',','.') }}</dd><dt>Fee agency / booking</dt><dd>Rp {{ number_format($row->agency_fee,0,',','.') }}</dd><dt>Fee ASISTA / booking</dt><dd>Rp {{ number_format($row->platform_fee,0,',','.') }}</dd><dt>Total pelanggan</dt><dd><strong>Rp {{ number_format($row->total,0,',','.') }}</strong></dd></dl>
<small>Nominal mengikuti kesepakatan saat booking. Fee ASISTA adalah pendapatan kotor, bukan laba bersih.</small>
@if($row->is_demo)<p>DEMO — bukan transaksi nyata.</p>@endif
@forelse($payments->get($row->id,collect()) as $payment)<p><strong>Midtrans: {{ $payment->status }}</strong><small>{{ $payment->order_id }}</small><small>{{ $payment->payment_type ?? 'Metode belum dipilih' }} · Rp {{ number_format($payment->amount,0,',','.') }}</small></p>@empty<p>Belum ada transaksi Midtrans.</p>@endforelse
@if(!$row->is_demo && $row->status === 'accepted' && $row->payment_status === 'unpaid' && !config('services.midtrans.enabled') && $payments->get($row->id,collect())->isEmpty())<form class="inline-form" method="post" action="/admin/bookings/{{ $row->id }}/payment">@csrf<label>Referensi transfer<input name="reference" required minlength="5" placeholder="Referensi transfer terverifikasi"></label><button>Konfirmasi pembayaran manual</button></form>@endif
</div></details></td></tr>@empty<tr><td colspan="6" class="empty">Belum ada booking.</td></tr>@endforelse
</tbody></table></div>
