@extends('admin.layout')
@section('content')
<link rel="stylesheet" href="/worker-cv.css?v=1">
@php($labels = ['verified'=>'Terverifikasi','pending'=>'Menunggu verifikasi','rejected'=>'Ditolak'])
@php($name = $profile->name ?? $user->name)
<main class="worker-cv">
<a class="cv-back" href="/admin?section=workers">← Kembali ke daftar pekerja</a>
<section class="panel cv-hero">
<div class="cv-photo">
@if($photo)<img src="{{ route('admin.document',$photo->id) }}" alt="Foto {{ $name }}">@else<div class="cv-initial">{{ mb_strtoupper(mb_substr($name,0,1)) }}<small>Foto belum diunggah</small></div>@endif
@if($photo)<span class="cv-photo-status">{{ $photo->status === 'verified' ? '✓ Foto terverifikasi' : 'Foto: '.($labels[$photo->status] ?? $photo->status) }}</span>@endif
</div>
<div class="cv-intro"><h1>{{ $name }} @if(($profile->verification ?? $user->verification) === 'verified')<span class="cv-check" title="Profil terverifikasi" aria-label="Profil terverifikasi">✓</span>@endif</h1>
<p class="cv-subtitle">{{ ['art'=>'Asisten Rumah Tangga','babysitter'=>'Babysitter'][$profile->category ?? $registration['category'] ?? ''] ?? 'Profil belum dilengkapi' }} <span>│</span> {{ $profile->city ?? $registration['city'] ?? 'Domisili belum diisi' }}</p>
<p><span class="cv-star">★</span> <strong>{{ $rating !== null ? number_format($rating,1) : 'Belum ada penilaian' }}</strong> @if($reviewCount)({{ $reviewCount }} ulasan)@endif <span class="cv-dot">·</span> Member sejak {{ \Carbon\Carbon::parse($user->created_at)->translatedFormat('M Y') }}</p>
<div class="cv-tags">@foreach($skills as $skill)<span>{{ $skill }}</span>@endforeach</div>
<p class="cv-muted">{{ $agency ? 'Melalui agency · '.$agency->name : ($profile ? 'Pekerja mandiri' : 'Status agency belum tersedia') }}</p>
</div>
<div class="cv-price"><a class="button cv-contact" href="mailto:{{ $user->email }}">Hubungi melalui email</a>
@if($profile)<div class="cv-price-box"><p><strong>Rp {{ number_format($profile->rate,0,',','.') }} / {{ ['hourly'=>'jam','daily'=>'hari','monthly'=>'bulan'][$profile->rate_unit] ?? $profile->rate_unit }}</strong><small>Tarif pekerja</small></p><p><strong>Rp {{ number_format($profile->agency_fee,0,',','.') }} / booking</strong><small>Fee agency</small></p></div><small>ⓘ Fee agency dikenakan sekali per booking, bukan dikalikan durasi.</small>@else<p>Tarif belum diisi oleh pekerja.</p>@endif
</div></section>
<nav class="cv-tabs" aria-label="Bagian CV"><a href="#profil">Profil</a><a href="#riwayat">Riwayat / CV</a><a href="#penilaian">Penilaian ({{ $reviewCount }})</a><a href="#jadwal">Jadwal & Ketersediaan</a></nav>
<div class="cv-columns">
<div><section class="panel cv-section" id="profil"><h2>● Tentang Saya</h2><p>{{ $profile->bio ?? 'Pendaftar belum melengkapi profil.' }}</p>
<div class="cv-facts"><div><small>Pengalaman</small><strong>{{ isset($profile->experience_years) ? $profile->experience_years.' tahun' : 'Belum diisi' }}</strong></div><div><small>Domisili</small><strong>{{ $profile->city ?? $registration['city'] ?? 'Belum diisi' }}</strong></div><div><small>Usia</small><strong>{{ !empty($registration['birth_date']) ? (int) \Carbon\Carbon::parse($registration['birth_date'])->age.' tahun' : 'Belum diisi' }}</strong></div><div><small>Pendidikan</small><strong>{{ $registration['education'] ?? 'Belum diisi' }}</strong></div><div><small>Jenis kelamin</small><strong>{{ $registration['gender'] ?? 'Belum diisi' }}</strong></div></div>
</section>
<section class="panel cv-section" id="riwayat"><h2>▣ Pengalaman Kerja</h2><p class="cv-muted">Riwayat pekerjaan selesai melalui ASISTA. Tidak termasuk booking demo.</p><div class="cv-timeline">@forelse($history as $booking)<article><h3>{{ ['art'=>'Asisten Rumah Tangga','babysitter'=>'Babysitter'][$profile->category] ?? 'Layanan keluarga' }} · Booking #{{ $booking->id }}</h3><small>{{ \Carbon\Carbon::parse($booking->starts_at)->format('d M Y') }} – {{ \Carbon\Carbon::parse($booking->ends_at)->format('d M Y') }}</small><p>{{ $booking->scope }}</p></article>@empty<p>Belum ada riwayat pekerjaan selesai yang tercatat.</p>@endforelse</div>@include('admin.cv-pagination',['page'=>$history,'anchor'=>'riwayat'])</section>
<section class="panel cv-section" id="penilaian"><h2>★ Penilaian</h2>@forelse($reviews as $review)<article class="cv-review"><strong>{{ $review->rating }} / 5</strong> <small>· {{ \Carbon\Carbon::parse($review->created_at)->format('d M Y') }}</small><p>{{ $review->comment }}</p></article>@empty<p>Belum ada ulasan dari transaksi aktual.</p>@endforelse @include('admin.cv-pagination',['page'=>$reviews,'anchor'=>'penilaian'])</section>
<section class="panel cv-section" id="jadwal"><h2>▦ Jadwal & Ketersediaan</h2><p><span class="cv-pill">{{ $profile ? ($profile->available ? 'Tersedia' : 'Tidak tersedia') : 'Belum diatur' }}</span> @if($profile){{ $profile->arrangement === 'live_in' ? 'Menginap / Live-in' : 'Pulang pergi / Live-out' }}@endif</p><small>Status ketersediaan mengikuti profil. Jadwal terisi di bawah berasal dari booking yang diterima atau sedang berlangsung.</small>@forelse($schedule as $booking)<p class="cv-review"><strong>Booking #{{ $booking->id }}</strong><br>{{ \Carbon\Carbon::parse($booking->starts_at)->format('d M Y H:i') }} – {{ \Carbon\Carbon::parse($booking->ends_at)->format('d M Y H:i') }}</p>@empty<p>Belum ada jadwal terisi mendatang.</p>@endforelse @include('admin.cv-pagination',['page'=>$schedule,'anchor'=>'jadwal'])</section></div>
<div><section class="panel cv-section"><h2>★ Keahlian</h2><ul class="cv-skill-list">@forelse($skills as $skill)<li><span>✓</span>{{ $skill }}</li>@empty<li>Keahlian belum diisi.</li>@endforelse</ul><h2>◉ Bahasa</h2><p class="cv-muted">Belum ada data kemampuan bahasa.</p><h2>▤ Sertifikasi</h2>@forelse($certifications as $certificate)<p class="cv-document">{{ $certificate }}</p>@empty<p class="cv-muted">Belum ada sertifikasi.</p>@endforelse</section>
<details class="panel cv-section"><summary>Data pendaftaran privat</summary><dl>@foreach($registration as $key=>$value)<dt>{{ ['phone'=>'Nomor handphone','province'=>'Provinsi','city'=>'Kota','district'=>'Kecamatan','address'=>'Alamat','postal_code'=>'Kode pos','birth_date'=>'Tanggal lahir','education'=>'Pendidikan','gender'=>'Jenis kelamin','experience'=>'Punya pengalaman','skills'=>'Keahlian','category'=>'Layanan','rate_unit'=>'Satuan tarif','arrangement'=>'Pola kerja'][$key] ?? $key }}</dt><dd>{{ is_array($value) ? implode(', ',$value) : (is_bool($value) ? ($value ? 'Ya' : 'Tidak') : ($value ?: '—')) }}</dd>@endforeach @if(!$registration)<p>Belum ada data tambahan.</p>@endif</dl></details></div>
<section class="panel cv-section cv-documents"><h2>▤ Dokumen privat</h2><p class="cv-muted">Hanya admin yang dapat mengakses dokumen. Setiap akses berkas dicatat dalam audit trail.</p>
@php($docLabels = ['ktp'=>'KTP','photo'=>'Foto diri','family_card'=>'Kartu Keluarga','skck'=>'SKCK','health_certificate'=>'Surat Kesehatan','training_certificate'=>'Sertifikat Pelatihan','supporting_document'=>'Dokumen pendukung'])
@forelse($documents as $document)<article class="cv-document"><strong>{{ $docLabels[$document->document_type] ?? 'Dokumen verifikasi' }}</strong><small class="cv-status status-{{ $document->status }}">{{ $labels[$document->status] ?? $document->status }}</small><small>{{ $document->original_name ?? 'Dokumen lama' }}</small><div class="cv-document-links"><a target="_blank" rel="noopener" href="{{ route('admin.document',$document->id) }}">Lihat dokumen ↗</a><a href="{{ route('admin.document',['id'=>$document->id,'download'=>1]) }}">Unduh</a></div>@if($document->note)<small>Catatan: {{ $document->note }}</small>@endif</article>@empty<p>Belum ada dokumen yang diunggah.</p>@endforelse
@foreach(['ktp'=>'KTP','photo'=>'Foto diri'] as $type=>$label)@unless($documents->contains('document_type',$type))<div class="cv-document"><strong>{{ $label }}</strong><small>Belum diunggah</small></div>@endunless @endforeach
</section></div><footer>CV ini disusun dari data profil dan aktivitas ASISTA. Informasi pribadi serta dokumen hanya tersedia bagi admin.</footer></main>
@endsection
